version: '3'
services:
  mongodb:
    image: bitnami/mongodb:4.4.4-debian-10-r5
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
    restart: always

  ratings:
    build: .
    container_name: ratings
    ports:
      - 8000:8000
    environment:
      - SERVICE_VERSION=v2
      - MONGO_DB_URL=mongodb://mongodb:27017/ratings
    depends_on:
      - mongodb
    restart: always
